# Generated by Django 6.0 on 2025-12-12 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shoe_gallery/')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='market.shoe')),
            ],
        ),
    ]
