# Generated by Django 6.0 on 2025-12-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_shoeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
