# Generated by Django 6.0 on 2025-12-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_shoe_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='currency',
            field=models.CharField(choices=[('EUR', '€'), ('USD', '$'), ('GBP', '£')], default='EUR', max_length=3),
        ),
    ]
